source_directory: "./converted_docs"
output_directory: "./Compatibility_Trainingdata"
output_formats:
  - json
  - csv
  - parquet
json_filename: "compatibility_training.json"
csv_filename: "compatibility_training.csv"
parquet_filename: "compatibility_training.parquet"
command_overview_filename: "command_overview.md"
metadata_filename: "generation_metadata.json"
log_level: "INFO"
